# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Config-System
version:      0.61
version_from: lib/Test/Config/System.pm
installdirs:  site
requires:
    File::Temp:                    0
    Test::Builder::Module:         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
